services:
  app:
    build: .
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - NAS_MOUNT_PATH=${NAS_MOUNT_PATH:-/nas/videos}
      - INITIAL_ADMIN_KEY_ID=${INITIAL_ADMIN_KEY_ID:-}
      - INITIAL_ADMIN_PUBLIC_KEY_FILE_NAME=${INITIAL_ADMIN_PUBLIC_KEY_FILE_NAME:-}
    volumes:
      - ${NAS_MOUNT_PATH:-./nas/videos}:/nas/videos
    restart: unless-stopped
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge 